=== fingolfin/gap-osx-binary/lib/gap/pkg/sgpviz/doc/gapdoc.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ==================================================================
     gapdoc.dtd - XML Document type definition for GAP documentation
     By Frank Lübeck and Max Neunhöffer
     ================================================================== -->

<!-- $Id: gapdoc.dtd,v 1.5 2002/05/02 20:39:58 gap Exp $ -->

<!-- Note that this definition goes "bottom-up" because entities can only
     be used after their definition in the file. -->


<!-- ==================================================================
     Some entities:
     ================================================================== -->

<!-- The standard XML entities: -->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;">


<!-- The following are necessary because these characters have special
     meanings in either XML or LaTeX: -->
     
<!ENTITY tamp 
  "<Alt Only='LaTeX'>\&amp;</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;amp;</Alt><Alt Not='HTML'>&amp;</Alt></Alt>">
<!ENTITY tlt 
  "<Alt Only='LaTeX'>{\textless}</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;lt;</Alt><Alt Not='HTML'>&lt;</Alt></Alt>">
<!ENTITY tgt 
  "<Alt Only='LaTeX'>{\textgreater}</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;gt;</Alt><Alt Not='HTML'>&gt;</Alt></Alt>">
<!ENTITY hash "<Alt Only='LaTeX'>\#</Alt><Alt Not='LaTeX'>#</Alt>">
<!ENTITY dollar "<Alt Only='LaTeX'>\$</Alt><Alt Not='LaTeX'>$</Alt>">
<!ENTITY percent 
  "<Alt Only='LaTeX'>\&#37;</Alt><Alt Not='LaTeX'>&#37;</Alt>">
<!ENTITY tilde 
  "<Alt Only='LaTeX'>{\textasciitilde}</Alt><Alt Not='LaTeX'>~</Alt>">
<!ENTITY bslash 
  "<Alt Only='LaTeX'>{\textbackslash}</Alt><Alt Not='LaTeX'>\</Alt>">
<!ENTITY obrace "<Alt Only='LaTeX'>\{</Alt><Alt Not='LaTeX'>{</Alt>">
<!ENTITY cbrace "<Alt Only='LaTeX'>\}</Alt><Alt Not='LaTeX'>}</Alt>">
<!ENTITY uscore 
  "<Alt Only='LaTeX'>{\textunderscore}</Alt><Alt Not='LaTeX'>_</Alt>">
<!ENTITY circum 
  "<Alt Only='LaTeX'>{\textasciicircum}</Alt><Alt Not='LaTeX'>^</Alt>">
<!ENTITY nbsp "<Alt Only='LaTeX'>~</Alt><Alt Not='LaTeX'>&#160;</Alt>">

<!-- ==================================================================
     Our predefined entities:
     ================================================================== -->

<!ENTITY GAP    "<Package>GAP</Package>">
<!ENTITY GAPDoc "<Package>GAPDoc</Package>">
<!ENTITY TeX    
  "<Alt Only='LaTeX'>{\TeX}</Alt><Alt Not='LaTeX'>TeX</Alt>">
<!ENTITY LaTeX  
  "<Alt Only='LaTeX'>{\LaTeX}</Alt><Alt Not='LaTeX'>LaTeX</Alt>">
<!ENTITY BibTeX 
  "<Alt Only='LaTeX'>{Bib\TeX}</Alt><Alt Not='LaTeX'>BibTeX</Alt>">
<!ENTITY MeatAxe "<Package>MeatAxe</Package>">
<!ENTITY XGAP   "<Package>XGAP</Package>">
<!ENTITY copyright 
  "<Alt Only='LaTeX'>{\copyright}</Alt><Alt Not='LaTeX'>(C)</Alt>">


<!-- ==================================================================
     The following describes the "innermost" documentation text which 
     can occur at various places in the document like for example
     section headings. It does neither contain further sectioning 
     elements nor environments like Enums or Lists. 
     ================================================================== -->

<!ENTITY % InnerText "#PCDATA |
                      Alt |
                      Emph | E |
                      Par | P | 
                      Keyword | K | Arg | A | Quoted | Q | Code | C | 
                      File | F | Button | B | Package |
                      M | Math | Display | 
                      Example | Listing | Log | Verb |
                      URL | Email | Homepage | Cite | Label | 
                      Ref | Index" >


<!ELEMENT Alt (%InnerText;)*>     <!-- This is only to allow "Only" and
                                       "Not" attributes for normal text -->
<!ATTLIST Alt Only CDATA #IMPLIED
              Not  CDATA #IMPLIED>

<!-- The following elements declare a certain block of InnerText to
     have a certain property. They are non-terminal and can contain
     any InnerText recursively. -->

<!ELEMENT Emph (%InnerText;)*>    <!-- Emphasize something -->
<!ELEMENT E    (%InnerText;)*>    <!-- the same as shortcut -->


<!-- The following is an empty element marking a paragraph boundary. -->

<!ELEMENT Par EMPTY>    <!-- this is intentionally empty! -->
<!ELEMENT P EMPTY>      <!-- this is intentionally empty! -->


<!-- The following elements mark a word or sentence to be of a certain
     kind, such that it can  be typeset differently. They are terminal
     elements that should only contain  character data. But we have to
     allow  Alt elements  for handling  special characters.  For these
     elements we introduce  a long name - which is  easy to remember -
     and a  short name - which  you may prefer because  of the shorter
     markup. -->

<!ELEMENT Keyword (#PCDATA|Alt)*>  <!-- Keyword -->
<!ELEMENT K (#PCDATA|Alt)*>        <!-- Keyword (shortcut) -->

<!ELEMENT Arg (#PCDATA|Alt)*>      <!-- Argument -->
<!ELEMENT A (#PCDATA|Alt)*>        <!-- Argument (shortcut) -->

<!ELEMENT Code (#PCDATA|Alt|A)*>   <!-- GAP code -->
<!ELEMENT C (#PCDATA|Alt|A)*>      <!-- GAP code (shortcut) -->

<!ELEMENT File (#PCDATA|Alt)*>     <!-- Filename -->
<!ELEMENT F (#PCDATA|Alt)*>        <!-- Filename (shortcut) -->

<!ELEMENT Button (#PCDATA|Alt)*>   <!-- "Button" (also Menu, Key) -->
<!ELEMENT B (#PCDATA|Alt)*>        <!-- "Button" (shortcut) -->

<!ELEMENT Package (#PCDATA|Alt)*>   <!-- A package name -->

<!ELEMENT Quoted (%InnerText;)*>   <!-- Quoted (in quotes) text -->
<!ELEMENT Q (%InnerText;)*>        <!-- Quoted text (shortcut) -->


<!-- The following elements contain mathematical formulae. They are 
     terminal elements that contain character data in TeX notation. -->

<!-- Math with well defined translation to text output -->
<!ELEMENT M (#PCDATA|A|Arg|Alt)*>
<!-- Normal TeX math mode formula -->
<!ELEMENT Math (#PCDATA|A|Arg|Alt)*>   
<!-- TeX displayed math mode formula -->
<!ELEMENT Display (#PCDATA|A|Arg|Alt)*>


<!-- The  following  elements  contain  GAP related  text  like  code,
     session  logs or  examples. They  are all  terminal elements  and
     consist of character data which is normally typeset verbatim. The
     different  types  of  the  elements only  control  how  they  are
     treated. -->

<!ELEMENT Example (#PCDATA)>  <!-- This is subject to the automatic 
                                   example checking mechanism -->
<!ELEMENT Log (#PCDATA)>      <!-- This not -->
<!ELEMENT Listing (#PCDATA)>  <!-- This is just for code listings -->
<!ATTLIST Listing Type CDATA #IMPLIED> <!-- a comment about the type of
                                            listed code, may appear in
                                            output -->

<!-- One  further  verbatim element,  this is truely  verbatim without
     any processing and intended  for ASCII substitutes of complicated
     displayed formulae or tables. -->

<!ELEMENT Verb  (#PCDATA)> 

<!-- The following  elements are  for cross-referencing  purposes like
     URLs, citations,  references, and  the index. All  these elements
     are  terminal and  need special  methods  to make  up the  actual
     output during document generation. -->

<!ELEMENT URL (#PCDATA|Alt)*>    <!-- Can we define this better? -->
<!ATTLIST URL Text CDATA #IMPLIED>   <!-- This is for output formats
                                          that have links like HTML -->

<!-- The following two are actually URLs, but the element name determines
     the type. -->
     
<!ELEMENT Email (#PCDATA|Alt)*>
<!ELEMENT Homepage (#PCDATA|Alt)*>

<!ELEMENT Cite EMPTY>
<!ATTLIST Cite Key CDATA #REQUIRED
               Where CDATA #IMPLIED>
               
<!ELEMENT Label EMPTY>
<!ATTLIST Label Name CDATA #REQUIRED>

<!ELEMENT Ref EMPTY>
<!ATTLIST Ref Func      CDATA #IMPLIED
              Oper      CDATA #IMPLIED
              Meth      CDATA #IMPLIED
              Filt      CDATA #IMPLIED
              Prop      CDATA #IMPLIED
              Attr      CDATA #IMPLIED
              Var       CDATA #IMPLIED
              Fam       CDATA #IMPLIED
              InfoClass CDATA #IMPLIED
              Chap      CDATA #IMPLIED
              Sect      CDATA #IMPLIED
              Subsect   CDATA #IMPLIED
              Appendix  CDATA #IMPLIED
              Text      CDATA #IMPLIED

              Label     CDATA #IMPLIED
              BookName  CDATA #IMPLIED
              Style (Text|Number) #IMPLIED>  <!-- normally automatic -->

<!-- Note that  only one attribute  of Ref is used  normally. BookName
     and  Style  can  be  specified in  addition  to  handle  external
     references and the typesetting style of the reference. -->

<!ELEMENT Index (%InnerText;)*>
<!ATTLIST Index Key    CDATA #IMPLIED
                Subkey CDATA #IMPLIED>


<!-- ==================================================================
     The following  describes the normal documentation  text which can
     occur  at various  places in  the document.  It does  not contain
     further sectioning elements. As  opposed to the InnerText element
     it can contain environments like enumerations, lists, and such.
     ================================================================== -->

<!ENTITY % Text "%InnerText; | List | Enum | Table">

<!ELEMENT Item ( %Text;)*>
<!ELEMENT Mark ( %InnerText;)*>
<!ELEMENT BigMark ( %InnerText;)*>

<!ELEMENT List ( ((Mark,Item)|(BigMark,Item)|Item)+ )>
<!ATTLIST List Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>
<!ELEMENT Enum ( Item+ )>
<!ATTLIST Enum Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>

<!ELEMENT Table ( Caption?, (Row | HorLine)+ )>
<!ATTLIST Table Label   CDATA #IMPLIED
                Only    CDATA #IMPLIED
                Not     CDATA #IMPLIED
                Align   CDATA #REQUIRED>    <!-- A TeX tabular string -->
                <!-- We allow | and l,c,r, nothing else -->
<!ELEMENT Row   ( Item+ )>
<!ELEMENT HorLine EMPTY>
<!ELEMENT Caption ( %InnerText;)*>

<!-- ==================================================================
     We start defining some things within the overall structure:
     ================================================================== -->

<!-- The TitlePage consists of several sub-elements: -->

<!ELEMENT TitlePage (Title, Subtitle?, Version?, Author+, Date?, Abstract?,
                     Copyright? , Acknowledgements? , Colophon? )>

<!ELEMENT Title (%Text;)*>
<!ELEMENT Subtitle (%Text;)*>
<!ELEMENT Version (%Text;)*>
<!ELEMENT Author (%Text;)*>    <!-- There may be more than one Author! -->
<!ELEMENT Date (%Text;)*>
<!ELEMENT Abstract (%Text;)*>
<!ELEMENT Copyright (%Text;)*>
<!ELEMENT Acknowledgements (%Text;)*>  
<!ELEMENT Colophon (%Text;)*>


<!-- The following things just specify some information about the
     corresponding parts of the Book: -->

<!ELEMENT TableOfContents EMPTY>
<!ELEMENT Bibliography EMPTY>
<!ATTLIST Bibliography Databases CDATA #REQUIRED
                       Style CDATA #IMPLIED>
<!ELEMENT TheIndex EMPTY>


<!-- ==================================================================
     Now we go on with the overall structure by defining the sectioning 
     structure, which includes the Synopsis element: 
     ================================================================== -->


<!ELEMENT Subsection (%Text;| Heading)*>
<!ATTLIST Subsection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT ManSection (((Func, Returns?) | (Oper, Returns?) | 
                       (Meth, Returns?) | (Filt, Returns?) | 
                       (Prop, Returns?) | (Attr, Returns?) |
                       Var | Fam | InfoClass)+, Description )>
<!ATTLIST ManSection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT Returns (%Text;)*>
<!ELEMENT Description (%Text;)*>


<!-- Note that  the ManSection element  is actually a  subsection with
     respect  to labelling,  referencing, and  counting of  sectioning
     elements. -->

<!ELEMENT Func EMPTY>
<!ATTLIST Func Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!-- Note  that Arg  contains the  full list  of arguments,  including
     optional  parts,  which  are   denoted  by  square  brackets  [].
     Arguments   are  separated   by  whitespace,   commas  count   as
     whitespace. -->

<!-- Note further that  even if Name and Label are  CDATA (and not ID)
     Label must make up a unique identifier. -->

<!ELEMENT Oper EMPTY>
<!ATTLIST Oper Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>
             
<!ELEMENT Meth EMPTY>
<!ATTLIST Meth Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Filt EMPTY>
<!ATTLIST Filt Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #IMPLIED
               Comm  CDATA #IMPLIED
               Type  CDATA #IMPLIED>  

<!ELEMENT Prop EMPTY>
<!ATTLIST Prop Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Attr EMPTY>
<!ATTLIST Attr Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Var  EMPTY>
<!ATTLIST Var  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT Fam  EMPTY>
<!ATTLIST Fam  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT InfoClass EMPTY>
<!ATTLIST InfoClass Name  CDATA #REQUIRED
                    Label CDATA #IMPLIED
                    Comm  CDATA #IMPLIED>


<!ELEMENT Heading (%InnerText;)*>

<!ELEMENT Section (%Text;| Heading | Subsection | ManSection)*>
<!ATTLIST Section Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!ELEMENT Chapter (%Text;| Heading | Section)*>
<!ATTLIST Chapter Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!-- Note that  the entity %InnerText; is  documentation that contains
     neither sectioning  elements nor environments  like enumerations,
     but  only  formulae,  labels, references,  citations,  and  other
     terminal elements. -->

<!ELEMENT Appendix (%Text;| Heading | Section)*>
<!ATTLIST Appendix Label CDATA #IMPLIED>   <!-- For reference purposes -->

<!-- Note that  an Appendix  is exactly  the same  as a  Chapter. They
     differ only in the numbering. -->

<!-- ==================================================================
     At last we define the overall structure of a gapdoc Book:
     ================================================================== -->

<!ELEMENT Body  ( %Text;| Chapter | Section )*>

<!ELEMENT Book (TitlePage,
                TableOfContents?,
                Body,
                Appendix*,
                Bibliography?,
                TheIndex?)>
<!ATTLIST Book Name CDATA #REQUIRED>
               
<!-- Note  that  the  entity  %Text; is  documentation  that  contains
     no  further sectioning  elements but  possibly environments  like
     enumerations,  and formulae,  labels, references,  and citations.
     -->

<!-- ============================================================== -->

=== fingolfin/gap-osx-binary/lib/gap/pkg/GradedModules/doc/GradedModulesForHomalg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
	  [
	  <!ENTITY see '<Alt Only="LaTeX">$\to$</Alt><Alt Not="LaTeX">--&gt;</Alt>'>
	  <!ENTITY GAP4 '<Package>GAP4</Package>'>
	  <!ENTITY Maple '<Package>Maple</Package>'>
	  <!ENTITY Mathematica '<Package>Mathematica</Package>'>
	  <!ENTITY Singular '<Package>Singular</Package>'>
	  <!ENTITY Plural '<Package>Plural</Package>'>
	  <!ENTITY Sage '<Package>Sage</Package>'>
	  <!ENTITY python '<Package>python</Package>'>
	  <!ENTITY cython '<Package>cython</Package>'>
	  <!ENTITY C '<Package>C</Package>'>
	  <!ENTITY MAGMA '<Package>MAGMA</Package>'>
	  <!ENTITY IO '<Package>IO</Package>'>
	  <!ENTITY homalg "<Package>homalg</Package>">
	  <!ENTITY LIRNG "<Package>LIRNG</Package>">
	  <!ENTITY LIMAP "<Package>LIMAP</Package>">
	  <!ENTITY LIMAT "<Package>LIMAT</Package>">
	  <!ENTITY COLEM "<Package>COLEM</Package>">
	  <!ENTITY LIMOD "<Package>LIMOD</Package>">
	  <!ENTITY LIMOR "<Package>LIMOR</Package>">
	  <!ENTITY LICPX "<Package>LICPX</Package>">
	  <!ENTITY LILIN "<Package>LILIN</Package>">
	  <!ENTITY LISHV "<Package>LISHV</Package>">
	  <!ENTITY LISCM "<Package>LISCM</Package>">
	  <!ENTITY LIMOS "<Package>LIMOS</Package>">
	  <!ENTITY ExamplesForHomalg "<Package>ExamplesForHomalg</Package>">
	  <!ENTITY alexander "<Package>alexander</Package>">
	  <!ENTITY Gauss "<Package>Gauss</Package>">
	  <!ENTITY GaussForHomalg "<Package>GaussForHomalg</Package>">
	  <!ENTITY IO_ForHomalg "<Package>IO_ForHomalg</Package>">
	  <!ENTITY RingsForHomalg "<Package>RingsForHomalg</Package>">
	  <!ENTITY LessGenerators "<Package>LessGenerators</Package>">
	  <!ENTITY Yoneda "<Package>Yoneda</Package>">
	  <!ENTITY Modules "<Package>Modules</Package>">
	  <!ENTITY GradedModules "<Package>GradedModules</Package>">
	  <!ENTITY Sheaves "<Package>Sheaves</Package>">
	  <!ENTITY SCO "<Package>SCO</Package>">
	  <!ENTITY GAPDoc "<Package>GAPDoc</Package>">
	  ]
	  >

<!--

  GradedModulesForHomalg.xml          GradedModules package documentation              Mohamed Barakat

  Copyright (C) 2008-2009, Mohamed Barakat, UniversitÃ¤t des Saarlandes

-->

<Book Name="GradedModules">

<#Include SYSTEM "title.xml">

<!--  TableOfContents  . . . . . .  generate a table of contents   -->
<TableOfContents/>

<!--  chapters of the book  -->
<Body>

<Index>&GradedModules;</Index>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "install.xml">
<#Include SYSTEM "QuickStart.xml">
<#Include SYSTEM "RingMaps.xml">
<#Include SYSTEM "GradedModules.xml">
<#Include SYSTEM "Tate.xml">
<#Include SYSTEM "examples.xml">
</Body>

<#Include SYSTEM "appendix.xml">

<Bibliography Databases="GradedModulesForHomalgBib.xml"/>

<!--  And finally an index as well   -->
<TheIndex/>

</Book>

=== fingolfin/gap-osx-binary/lib/gap/pkg/atlasrep/doc/main.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- %W  main.xml        GAP 4 package AtlasRep             Thomas Breuer -->
<!-- %Y  Copyright 2006, Lehrstuhl D für Mathematik, RWTH Aachen, Germany -->

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
   [ <!ENTITY ATLAS "<Package>ATLAS</Package>">

     <!ENTITY ATLASSERVER "<URL>http://brauer.maths.qmul.ac.uk/Atlas</URL>">
     <!ENTITY ATLASREPHOME "http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep">
     <!ENTITY WILSONMAIL "<Email>R.A.Wilson@qmul.ac.uk</Email>">

     <!ENTITY mdash "<Alt Only='HTML'>&#8212;</Alt><Alt Not='HTML'>---</Alt>">

     <!ENTITY VERSIONNUMBER "1.5">
     <!ENTITY RELEASEMONTH "July">
     <!ENTITY RELEASEYEAR "2011">
   ]>

<Book Name="AtlasRep">

<TitlePage>
  <Title><Package>AtlasRep</Package> &mdash; A GAP 4 Package<Index>AtlasRep</Index></Title>
  <Version>(Version &VERSIONNUMBER;)
  </Version>
  <Author>Robert A. Wilson
    &WILSONMAIL;
    <Homepage>http://www.maths.qmw.ac.uk/~raw</Homepage>
  </Author>
  <Author>Richard A. Parker
    <Email>richpark@gmx.co.uk</Email>
  </Author>
  <Author>Simon Nickerson
    <Email>simonn@maths.bham.ac.uk</Email>
    <Homepage>http://web.mat.bham.ac.uk/S.Nickerson</Homepage>
  </Author>
  <Author>John N. Bray
    <Email>J.N.Bray@qmul.ac.uk</Email>
    <Homepage>http://www.maths.qmw.ac.uk/~jnb</Homepage>
  </Author>
  <Author>Thomas Breuer
    <Email>sam@Math.RWTH-Aachen.De</Email>
    <Homepage>http://www.math.rwth-aachen.de/~Thomas.Breuer</Homepage>
  </Author>
  <Copyright>
    &copyright; 2002&ndash;2011
    <P/>
    This package may be distributed under the terms and conditions of the
    GNU Public License Version 3 or later,
    see <URL>http://www.gnu.org/licenses</URL>.
  </Copyright>
</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "introduc.xml">

<#Include SYSTEM "tutorial.xml">

<#Include SYSTEM "interfac.xml">

<#Include SYSTEM "atlasrep.xml">

<#Include SYSTEM "extend.xml">

<#Include SYSTEM "utils.xml">

<#Include SYSTEM "technica.xml">

</Body>

<Bibliography Databases="manualbib.xml,../../../doc/manualbib.xml,../../ctbllib/doc/manualbib.xml"/>

<TheIndex/>

</Book>

<!-- ==================================================================== -->

=== fingolfin/gap-osx-binary/lib/gap/pkg/ctbllib/doc/main.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
   [ <!ENTITY CTblLib "<Package>CTblLib</Package>">
     <!ENTITY ATLAS "<Package>Atlas</Package>">
     <!ENTITY MOC "<Package>MOC</Package>">
     <!ENTITY CAS "<Package>CAS</Package>">

     <!ENTITY AUTHOREMAIL "<Email>sam@math.rwth-aachen.de</Email>">

     <!ENTITY mdash "<Alt Only='HTML'>&#8212;</Alt><Alt Not='HTML'>---</Alt>">

     <!ENTITY VERSIONNUMBER "1.2.1">
     <!ENTITY RELEASEMONTH "May">
     <!ENTITY RELEASEYEAR "2012">
   ]>

<Book Name="CTblLib">

<TitlePage>
  <Title>The &GAP; Character Table Library<Index>CTblLib</Index></Title>
  <Version>(Version &VERSIONNUMBER;)
  </Version>
  <Author>Thomas Breuer
    &AUTHOREMAIL;
  <!--   <Email>sam@Math.RWTH-Aachen.De</Email>   -->
    <Homepage>http://www.math.rwth-aachen.de/~Thomas.Breuer</Homepage>
  </Author>
  <Copyright>
    &copyright; 2003&ndash;2012
    <P/>
    This package may be distributed under the terms and conditions of the
    GNU Public License Version 3 or later,
    see <URL>http://www.gnu.org/licenses</URL>.
  </Copyright>
</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "introduc.xml">

<#Include SYSTEM "tutorial.xml">

<#Include SYSTEM "interfac.xml">

<#Include SYSTEM "ctbllibr.xml">

<#Include SYSTEM "construc.xml">

<#Include SYSTEM "ctblothe.xml">

</Body>


<Bibliography Databases="manualbib.xml,../../../doc/manualbib.xml,../../atlasrep/doc/manualbib.xml,../../Browse/doc/browsebib.xml"/>

<TheIndex/>

</Book>

<!-- ==================================================================== -->

=== fingolfin/gap-osx-binary/lib/gap/pkg/PolymakeInterface/doc/PolymakeInterface.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- This is an automatically generated file. -->
<!DOCTYPE Book SYSTEM "gapdoc.dtd"
[
<!ENTITY see '<Alt Only="LaTeX">$	o$</Alt><Alt Not="LaTeX">--&gt;</Alt>'>
<!ENTITY PolymakeInterface '<Package>PolymakeInterface</Package>'>
]
>
<Book Name="PolymakeInterface">
<#Include SYSTEM "title.xml">
<TableOfContents/>
<Body>
<Index>&PolymakeInterface;</Index>
<#Include SYSTEM "AutoDocMainFile.xml">
</Body>
<Bibliography Databases="PolymakeInterface.bib"/>
<TheIndex/>
</Book>

=== fingolfin/gap-osx-binary/lib/gap/pkg/io-4.3.1/doc/io.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd">

<!--

  io.xml          IO package documentation                Max Neunhoeffer

  Copyright (C) 2006-2012  Max Neunhoeffer, Lehrstuhl D f. Math., RWTH Aachen
  This file is free software, see license information at the end.

-->

<Book Name="IO">

<TitlePage>
    <Title>GAP 4 Package <Package>IO</Package></Title>
    <Subtitle>Bindings for low level C library I/O routines</Subtitle>
    <Version>
      Version <#Include SYSTEM "../VERSION">
    </Version>
    <Author>Max Neunhöffer
<Address>
School of Mathematics and Statistics
Mathematical Institute
University of St Andrews
North Haugh
St Andrews, Fife KY16 9SS
Scotland, UK
</Address>
    <Email>neunhoef@mcs.st-and.ac.uk</Email>
    <Homepage>http://www-groups.mcs.st-and.ac.uk/&tilde;neunhoef</Homepage>
    </Author>
    <Date>March 2014</Date>

<Copyright>
    &copyright; 2005-2012 by Max Neunhöffer<P/>

  This package may be distributed under the terms and conditions of the
  GNU Public License Version 3 or later.
</Copyright>
</TitlePage>

<!--  TableOfContents  . . . . . .  generate a table of contents   -->
<TableOfContents/>

<!--  The only chapter of the book  --> 
<Body>
<#Include SYSTEM "main.xml">
</Body>

<!--  We do not need a bibliography  -->
<!-- <Bibliography Databases="edim"/>-->

<!--  And finally an index as well   -->
<TheIndex/>

</Book>

<!--
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

=== fingolfin/gap-osx-binary/lib/gap/pkg/idrel-2.31/doc/manual.xml
<!-- ------------------------------------------------------------------- -->
<!--                                                                     -->
<!--  manual.xml         IdRel documentation              Chris Wensley  -->
<!--                                                    & Anne Heyworth  -->
<!--                                                                     -->
<!--  version 2.31, 01/06/2015                                           -->
<!--                                                                     -->
<!--  Copyright (C) 1999-2015, Anne Heyworth and Chris Wensley,          --> 
<!--  School of Computer Science, Bangor University, U.K.                --> 
<!--                                                                     -->
<!-- ------------------------------------------------------------------- -->

<?xml version="1.0" encoding="UTF-8"?>

<!-- Reading data chunk from the PackageInfo.g file --> 

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
  [<!ENTITY idrel "<Package>IdRel</Package>"> 
   <#Include Label="PKGVERSIONDATA"> 
  ]> 

<!-- The documentation to the IdRel package. -->

<Book Name="IdRel"> 

<TitlePage>
  <Title>&idrel;</Title>
  <Subtitle>A package for Identities among Relators</Subtitle>
  <Version>Version &VERSION;</Version>   
  <Date>&RELEASEDATE;</Date> 
  <Author> Anne Heyworth </Author>    
  <Author> Chris Wensley
    <Email>c.d.wensley@bangor.ac.uk</Email>
    <Homepage>http://pages.bangor.ac.uk/~mas023/</Homepage>
    <Address>
      School of Computer Science, Bangor University,<Br/>
      Dean Street, Bangor, Gwynedd, LL57 1UT, U.K.
    </Address>
  </Author>

<Abstract>
The &idrel; package was originally implemented in 1999, 
using the &GAP; 3 language, 
when the first author was studying for a Ph.D. in Bangor.
<P/>
This package is designed to compute a minimal set of generators
for the module of the identities among relators of a group presentation. 
It does this using
<List>
<Item>
rewriting and logged rewriting: a self-contained implementation
of the Knuth-Bendix process using the monoid presentation
associated to the group presentation;
</Item>
<Item>
monoid polynomials: an implementation of the monoid ring;
</Item>
<Item>
module polynomials: an implementation of the right module
over this monoid generated by the relators.
</Item>
<Item>
Y-sequences: used as a <E>rewriting</E> way of representing
elements of a free crossed module
(products of conjugates of group relators and inverse relators).
</Item>
</List>
<P/>
&idrel; became an accepted &GAP; package in May 2015. 
<P/>
Bug reports, suggestions and comments are, of course, welcome. 
Please contact the second author at     
<Email>c.d.wensley@bangor.ac.uk</Email>.
</Abstract>

<Copyright> 
<Index>License</Index>
&copyright; 1999-2015 Anne Heyworth and Chris Wensley <P/>

&idrel; is free software; you can redistribute it 
and/or modify it under the terms of the 
<URL Text="GNU General Public License">http://www.fsf.org/licenses/gpl.html</URL> 
as published by the Free Software Foundation; 
either version 2 of the License, or (at your option) any later version.
</Copyright>

<Acknowledgements>
This documentation was prepared with the <Package>GAPDoc</Package> 
package of Frank L&#xfc;beck and Max Neunh&#xf6;ffer. 
</Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "rws.xml">
<#Include SYSTEM "logrws.xml">
<#Include SYSTEM "monpoly.xml">
<#Include SYSTEM "modpoly.xml">

</Body>

<Bibliography Databases="idrelbib.xml"/>
<!--  <Bibliography Databases="manual"/> --> 

<TheIndex/>

</Book>
