=== fingolfin/gap-osx-binary/lib/gap/pkg/sgpviz/doc/gapdoc.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ==================================================================
     gapdoc.dtd - XML Document type definition for GAP documentation
     By Frank Lübeck and Max Neunhöffer
     ================================================================== -->

<!-- $Id: gapdoc.dtd,v 1.5 2002/05/02 20:39:58 gap Exp $ -->

<!-- Note that this definition goes "bottom-up" because entities can only
     be used after their definition in the file. -->


<!-- ==================================================================
     Some entities:
     ================================================================== -->

<!-- The standard XML entities: -->

<!ENTITY lt     "&#38;#60;"> 
<!ENTITY gt     "&#62;"> 
<!ENTITY amp    "&#38;#38;"> 
<!ENTITY apos   "&#39;"> 
<!ENTITY quot   "&#34;">


<!-- The following are necessary because these characters have special
     meanings in either XML or LaTeX: -->
     
<!ENTITY tamp 
  "<Alt Only='LaTeX'>\&amp;</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;amp;</Alt><Alt Not='HTML'>&amp;</Alt></Alt>">
<!ENTITY tlt 
  "<Alt Only='LaTeX'>{\textless}</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;lt;</Alt><Alt Not='HTML'>&lt;</Alt></Alt>">
<!ENTITY tgt 
  "<Alt Only='LaTeX'>{\textgreater}</Alt><Alt Not='LaTeX'><Alt Only='HTML'>&amp;gt;</Alt><Alt Not='HTML'>&gt;</Alt></Alt>">
<!ENTITY hash "<Alt Only='LaTeX'>\#</Alt><Alt Not='LaTeX'>#</Alt>">
<!ENTITY dollar "<Alt Only='LaTeX'>\$</Alt><Alt Not='LaTeX'>$</Alt>">
<!ENTITY percent 
  "<Alt Only='LaTeX'>\&#37;</Alt><Alt Not='LaTeX'>&#37;</Alt>">
<!ENTITY tilde 
  "<Alt Only='LaTeX'>{\textasciitilde}</Alt><Alt Not='LaTeX'>~</Alt>">
<!ENTITY bslash 
  "<Alt Only='LaTeX'>{\textbackslash}</Alt><Alt Not='LaTeX'>\</Alt>">
<!ENTITY obrace "<Alt Only='LaTeX'>\{</Alt><Alt Not='LaTeX'>{</Alt>">
<!ENTITY cbrace "<Alt Only='LaTeX'>\}</Alt><Alt Not='LaTeX'>}</Alt>">
<!ENTITY uscore 
  "<Alt Only='LaTeX'>{\textunderscore}</Alt><Alt Not='LaTeX'>_</Alt>">
<!ENTITY circum 
  "<Alt Only='LaTeX'>{\textasciicircum}</Alt><Alt Not='LaTeX'>^</Alt>">
<!ENTITY nbsp "<Alt Only='LaTeX'>~</Alt><Alt Not='LaTeX'>&#160;</Alt>">

<!-- ==================================================================
     Our predefined entities:
     ================================================================== -->

<!ENTITY GAP    "<Package>GAP</Package>">
<!ENTITY GAPDoc "<Package>GAPDoc</Package>">
<!ENTITY TeX    
  "<Alt Only='LaTeX'>{\TeX}</Alt><Alt Not='LaTeX'>TeX</Alt>">
<!ENTITY LaTeX  
  "<Alt Only='LaTeX'>{\LaTeX}</Alt><Alt Not='LaTeX'>LaTeX</Alt>">
<!ENTITY BibTeX 
  "<Alt Only='LaTeX'>{Bib\TeX}</Alt><Alt Not='LaTeX'>BibTeX</Alt>">
<!ENTITY MeatAxe "<Package>MeatAxe</Package>">
<!ENTITY XGAP   "<Package>XGAP</Package>">
<!ENTITY copyright 
  "<Alt Only='LaTeX'>{\copyright}</Alt><Alt Not='LaTeX'>(C)</Alt>">


<!-- ==================================================================
     The following describes the "innermost" documentation text which 
     can occur at various places in the document like for example
     section headings. It does neither contain further sectioning 
     elements nor environments like Enums or Lists. 
     ================================================================== -->

<!ENTITY % InnerText "#PCDATA |
                      Alt |
                      Emph | E |
                      Par | P | 
                      Keyword | K | Arg | A | Quoted | Q | Code | C | 
                      File | F | Button | B | Package |
                      M | Math | Display | 
                      Example | Listing | Log | Verb |
                      URL | Email | Homepage | Cite | Label | 
                      Ref | Index" >


<!ELEMENT Alt (%InnerText;)*>     <!-- This is only to allow "Only" and
                                       "Not" attributes for normal text -->
<!ATTLIST Alt Only CDATA #IMPLIED
              Not  CDATA #IMPLIED>

<!-- The following elements declare a certain block of InnerText to
     have a certain property. They are non-terminal and can contain
     any InnerText recursively. -->

<!ELEMENT Emph (%InnerText;)*>    <!-- Emphasize something -->
<!ELEMENT E    (%InnerText;)*>    <!-- the same as shortcut -->


<!-- The following is an empty element marking a paragraph boundary. -->

<!ELEMENT Par EMPTY>    <!-- this is intentionally empty! -->
<!ELEMENT P EMPTY>      <!-- this is intentionally empty! -->


<!-- The following elements mark a word or sentence to be of a certain
     kind, such that it can  be typeset differently. They are terminal
     elements that should only contain  character data. But we have to
     allow  Alt elements  for handling  special characters.  For these
     elements we introduce  a long name - which is  easy to remember -
     and a  short name - which  you may prefer because  of the shorter
     markup. -->

<!ELEMENT Keyword (#PCDATA|Alt)*>  <!-- Keyword -->
<!ELEMENT K (#PCDATA|Alt)*>        <!-- Keyword (shortcut) -->

<!ELEMENT Arg (#PCDATA|Alt)*>      <!-- Argument -->
<!ELEMENT A (#PCDATA|Alt)*>        <!-- Argument (shortcut) -->

<!ELEMENT Code (#PCDATA|Alt|A)*>   <!-- GAP code -->
<!ELEMENT C (#PCDATA|Alt|A)*>      <!-- GAP code (shortcut) -->

<!ELEMENT File (#PCDATA|Alt)*>     <!-- Filename -->
<!ELEMENT F (#PCDATA|Alt)*>        <!-- Filename (shortcut) -->

<!ELEMENT Button (#PCDATA|Alt)*>   <!-- "Button" (also Menu, Key) -->
<!ELEMENT B (#PCDATA|Alt)*>        <!-- "Button" (shortcut) -->

<!ELEMENT Package (#PCDATA|Alt)*>   <!-- A package name -->

<!ELEMENT Quoted (%InnerText;)*>   <!-- Quoted (in quotes) text -->
<!ELEMENT Q (%InnerText;)*>        <!-- Quoted text (shortcut) -->


<!-- The following elements contain mathematical formulae. They are 
     terminal elements that contain character data in TeX notation. -->

<!-- Math with well defined translation to text output -->
<!ELEMENT M (#PCDATA|A|Arg|Alt)*>
<!-- Normal TeX math mode formula -->
<!ELEMENT Math (#PCDATA|A|Arg|Alt)*>   
<!-- TeX displayed math mode formula -->
<!ELEMENT Display (#PCDATA|A|Arg|Alt)*>


<!-- The  following  elements  contain  GAP related  text  like  code,
     session  logs or  examples. They  are all  terminal elements  and
     consist of character data which is normally typeset verbatim. The
     different  types  of  the  elements only  control  how  they  are
     treated. -->

<!ELEMENT Example (#PCDATA)>  <!-- This is subject to the automatic 
                                   example checking mechanism -->
<!ELEMENT Log (#PCDATA)>      <!-- This not -->
<!ELEMENT Listing (#PCDATA)>  <!-- This is just for code listings -->
<!ATTLIST Listing Type CDATA #IMPLIED> <!-- a comment about the type of
                                            listed code, may appear in
                                            output -->

<!-- One  further  verbatim element,  this is truely  verbatim without
     any processing and intended  for ASCII substitutes of complicated
     displayed formulae or tables. -->

<!ELEMENT Verb  (#PCDATA)> 

<!-- The following  elements are  for cross-referencing  purposes like
     URLs, citations,  references, and  the index. All  these elements
     are  terminal and  need special  methods  to make  up the  actual
     output during document generation. -->

<!ELEMENT URL (#PCDATA|Alt)*>    <!-- Can we define this better? -->
<!ATTLIST URL Text CDATA #IMPLIED>   <!-- This is for output formats
                                          that have links like HTML -->

<!-- The following two are actually URLs, but the element name determines
     the type. -->
     
<!ELEMENT Email (#PCDATA|Alt)*>
<!ELEMENT Homepage (#PCDATA|Alt)*>

<!ELEMENT Cite EMPTY>
<!ATTLIST Cite Key CDATA #REQUIRED
               Where CDATA #IMPLIED>
               
<!ELEMENT Label EMPTY>
<!ATTLIST Label Name CDATA #REQUIRED>

<!ELEMENT Ref EMPTY>
<!ATTLIST Ref Func      CDATA #IMPLIED
              Oper      CDATA #IMPLIED
              Meth      CDATA #IMPLIED
              Filt      CDATA #IMPLIED
              Prop      CDATA #IMPLIED
              Attr      CDATA #IMPLIED
              Var       CDATA #IMPLIED
              Fam       CDATA #IMPLIED
              InfoClass CDATA #IMPLIED
              Chap      CDATA #IMPLIED
              Sect      CDATA #IMPLIED
              Subsect   CDATA #IMPLIED
              Appendix  CDATA #IMPLIED
              Text      CDATA #IMPLIED

              Label     CDATA #IMPLIED
              BookName  CDATA #IMPLIED
              Style (Text|Number) #IMPLIED>  <!-- normally automatic -->

<!-- Note that  only one attribute  of Ref is used  normally. BookName
     and  Style  can  be  specified in  addition  to  handle  external
     references and the typesetting style of the reference. -->

<!ELEMENT Index (%InnerText;)*>
<!ATTLIST Index Key    CDATA #IMPLIED
                Subkey CDATA #IMPLIED>


<!-- ==================================================================
     The following  describes the normal documentation  text which can
     occur  at various  places in  the document.  It does  not contain
     further sectioning elements. As  opposed to the InnerText element
     it can contain environments like enumerations, lists, and such.
     ================================================================== -->

<!ENTITY % Text "%InnerText; | List | Enum | Table">

<!ELEMENT Item ( %Text;)*>
<!ELEMENT Mark ( %InnerText;)*>
<!ELEMENT BigMark ( %InnerText;)*>

<!ELEMENT List ( ((Mark,Item)|(BigMark,Item)|Item)+ )>
<!ATTLIST List Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>
<!ELEMENT Enum ( Item+ )>
<!ATTLIST Enum Only CDATA #IMPLIED
               Not  CDATA #IMPLIED>

<!ELEMENT Table ( Caption?, (Row | HorLine)+ )>
<!ATTLIST Table Label   CDATA #IMPLIED
                Only    CDATA #IMPLIED
                Not     CDATA #IMPLIED
                Align   CDATA #REQUIRED>    <!-- A TeX tabular string -->
                <!-- We allow | and l,c,r, nothing else -->
<!ELEMENT Row   ( Item+ )>
<!ELEMENT HorLine EMPTY>
<!ELEMENT Caption ( %InnerText;)*>

<!-- ==================================================================
     We start defining some things within the overall structure:
     ================================================================== -->

<!-- The TitlePage consists of several sub-elements: -->

<!ELEMENT TitlePage (Title, Subtitle?, Version?, Author+, Date?, Abstract?,
                     Copyright? , Acknowledgements? , Colophon? )>

<!ELEMENT Title (%Text;)*>
<!ELEMENT Subtitle (%Text;)*>
<!ELEMENT Version (%Text;)*>
<!ELEMENT Author (%Text;)*>    <!-- There may be more than one Author! -->
<!ELEMENT Date (%Text;)*>
<!ELEMENT Abstract (%Text;)*>
<!ELEMENT Copyright (%Text;)*>
<!ELEMENT Acknowledgements (%Text;)*>  
<!ELEMENT Colophon (%Text;)*>


<!-- The following things just specify some information about the
     corresponding parts of the Book: -->

<!ELEMENT TableOfContents EMPTY>
<!ELEMENT Bibliography EMPTY>
<!ATTLIST Bibliography Databases CDATA #REQUIRED
                       Style CDATA #IMPLIED>
<!ELEMENT TheIndex EMPTY>


<!-- ==================================================================
     Now we go on with the overall structure by defining the sectioning 
     structure, which includes the Synopsis element: 
     ================================================================== -->


<!ELEMENT Subsection (%Text;| Heading)*>
<!ATTLIST Subsection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT ManSection (((Func, Returns?) | (Oper, Returns?) | 
                       (Meth, Returns?) | (Filt, Returns?) | 
                       (Prop, Returns?) | (Attr, Returns?) |
                       Var | Fam | InfoClass)+, Description )>
<!ATTLIST ManSection Label CDATA #IMPLIED> <!-- For reference purposes -->

<!ELEMENT Returns (%Text;)*>
<!ELEMENT Description (%Text;)*>


<!-- Note that  the ManSection element  is actually a  subsection with
     respect  to labelling,  referencing, and  counting of  sectioning
     elements. -->

<!ELEMENT Func EMPTY>
<!ATTLIST Func Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!-- Note  that Arg  contains the  full list  of arguments,  including
     optional  parts,  which  are   denoted  by  square  brackets  [].
     Arguments   are  separated   by  whitespace,   commas  count   as
     whitespace. -->

<!-- Note further that  even if Name and Label are  CDATA (and not ID)
     Label must make up a unique identifier. -->

<!ELEMENT Oper EMPTY>
<!ATTLIST Oper Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>
             
<!ELEMENT Meth EMPTY>
<!ATTLIST Meth Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Filt EMPTY>
<!ATTLIST Filt Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #IMPLIED
               Comm  CDATA #IMPLIED
               Type  CDATA #IMPLIED>  

<!ELEMENT Prop EMPTY>
<!ATTLIST Prop Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Attr EMPTY>
<!ATTLIST Attr Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Arg   CDATA #REQUIRED
               Comm  CDATA #IMPLIED>

<!ELEMENT Var  EMPTY>
<!ATTLIST Var  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT Fam  EMPTY>
<!ATTLIST Fam  Name  CDATA #REQUIRED
               Label CDATA #IMPLIED
               Comm  CDATA #IMPLIED>

<!ELEMENT InfoClass EMPTY>
<!ATTLIST InfoClass Name  CDATA #REQUIRED
                    Label CDATA #IMPLIED
                    Comm  CDATA #IMPLIED>


<!ELEMENT Heading (%InnerText;)*>

<!ELEMENT Section (%Text;| Heading | Subsection | ManSection)*>
<!ATTLIST Section Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!ELEMENT Chapter (%Text;| Heading | Section)*>
<!ATTLIST Chapter Label CDATA #IMPLIED>    <!-- For reference purposes -->


<!-- Note that  the entity %InnerText; is  documentation that contains
     neither sectioning  elements nor environments  like enumerations,
     but  only  formulae,  labels, references,  citations,  and  other
     terminal elements. -->

<!ELEMENT Appendix (%Text;| Heading | Section)*>
<!ATTLIST Appendix Label CDATA #IMPLIED>   <!-- For reference purposes -->

<!-- Note that  an Appendix  is exactly  the same  as a  Chapter. They
     differ only in the numbering. -->

<!-- ==================================================================
     At last we define the overall structure of a gapdoc Book:
     ================================================================== -->

<!ELEMENT Body  ( %Text;| Chapter | Section )*>

<!ELEMENT Book (TitlePage,
                TableOfContents?,
                Body,
                Appendix*,
                Bibliography?,
                TheIndex?)>
<!ATTLIST Book Name CDATA #REQUIRED>
               
<!-- Note  that  the  entity  %Text; is  documentation  that  contains
     no  further sectioning  elements but  possibly environments  like
     enumerations,  and formulae,  labels, references,  and citations.
     -->

<!-- ============================================================== -->

=== fingolfin/gap-osx-binary/lib/gap/pkg/float-0.6.2/doc/float.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd" [
 <!ENTITY see '<Alt Only="LaTeX">$\to$</Alt><Alt Not="LaTeX">--&tgt;</Alt>'>
 <#Include Label="Version">
]>
<Book Name="FLOAT">

<TitlePage>
  <Title>Floating-point numbers</Title>
  <Version>Version &Version;</Version>
  <TitleComment>
    MPFR- and CXSC-based library for GAP
  </TitleComment>
  <Author>Laurent Bartholdi
          <Email><Alt Only="HTML">laurent dot bartholdi at gmail dot com</Alt>
		 <Alt Not="HTML">laurent.bartholdi@gmail.com</Alt></Email> 
	  <Homepage>http://www.uni-math.gwdg.de/laurent/</Homepage>
  </Author>
  <Date>&Date;</Date>
  <Address>
  Mathematisches Institut<Br/>Bunsenstraße 3-5<Br/>D-37073 Göttingen<Br/>Germany
  </Address>
  <Abstract>
    This document describes the package <Package>Float</Package>, which
    implements in &GAP; arbitrary-precision floating-point numbers.
  <Alt Only="HTML">
  <P/>
  The computer algebra system &GAP; is available at
  <URL>http://gap-system.org</URL>.
  <P/>
  This documentation for <Package>Float</Package> is available at
  <URL>http://laurentbartholdi.github.com/float/manual.pdf</URL> in PDF format, and may be
  accessed online at <URL>http://laurentbartholdi.github.com/float/</URL>.
  <P/>
  The latest release of the package may be downloaded as
  <URL>http://www.uni-math.gwdg.de/laurent/archive/float-&Version;.tar.gz</URL> (tar, gzipped).
  The latest repository version (possibly unstable) may be downloaded as
  <URL>https://github.com/laurentbartholdi/float/tarball/master</URL> (tar, gzipped),
  <URL>https://github.com/laurentbartholdi/float.git</URL> (git repository), or
  explored at <URL>https://github.com/laurentbartholdi/float/tree/master/</URL>.
  </Alt>
  <P/>
    For comments or questions on <Package>Float</Package> please contact
    the author.
  </Abstract>
  <Copyright>&copyright; 2011-2014 by Laurent Bartholdi
  </Copyright>
  <Acknowledgements>Part of this work is supported by the "Swiss
  National Fund for Scientific Research (SNF)", the "German National Science Foundation (DFG)",
  and the Courant Research Centre "Higher Order Structures" of the University of Göttingen.
  </Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>

<Chapter><Heading>Licensing</Heading>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or any
later version.

<P/> This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

<P/> You should have received a copy of the GNU General Public
License along with this program, in the file COPYING.  If not, see
<URL>http://www.gnu.org/licenses/</URL>.

</Chapter>

<Chapter Label="floatpackage"><Heading>Float package</Heading>

<Section Label="sample"><Heading>A sample run</Heading>

The extended floating-point capabilities of &GAP; are installed by loading the package
via <C>LoadPackage("float");</C> and selecting new floating-point handlers via
<C>SetFloats(MPFR)</C>, <C>SetFloats(MPFI)</C>, <C>SetFloats(MPC)</C> or<C>SetFloats(CXSC)</C>,
depending on whether high-precision real, interval or complex arithmetic are desired, or
whether a fast package containing all four real/complex element/interval arithmetic is desired:
<Example><![CDATA[
gap> LoadPackage("float");
Loading FLOAT 0.3 ...
true
gap> SetFloats(MPFR); # floating-point
gap> x := 4*Atan(1.0);
.314159e1
gap> Sin(x);
.169569e-30
gap> SetFloats(MPFR,1000); # 1000 bits
gap> x := 4*Atan(1.0);
.314159e1
gap> Sin(x);
.125154e-300
gap> String(x,300);
".3141592653589793238462643383279502884197169399375105820974944592307816406286\
208998628034825342117067982148086513282306647093844609550582231725359408128481\
117450284102701938521105559644622948954930381964428810975665933446128475648233\
78678316527120190914564856692346034861045432664821339360726024914127e1"
gap>
gap> SetFloats(MPFI); # intervals
gap> x := 4*Atan(1.0);
.314159e1(99)
gap> AbsoluteDiameter(x); Sup(x); Inf(x);
.100441e-29
.314159e1
.314159e1
gap> Sin(x);
-.140815e-29(97)
gap> 0.0 in last;
true
gap> 1.0; # exact representation
.1e1(∞)
gap> IncreaseInterval(last,0.001); # now only 8 significant bits
.1e1(8)
gap> IncreaseInterval(last,-0.002); # now becomes empty
∅
gap> MinimalPolynomial(Rationals,Sqrt(2.0));
-2*x_1^2+1
gap> Cyc(last);
E(8)-E(8)^3
gap>
gap> SetFloats(MPC); # complex numbers
]]></Example>

</Section>

</Chapter>

<Chapter Label="poly"><Heading>Polynomials</Heading>

<Section><Heading>The Floats pseudo-field</Heading>

Polynomials with floating-point coefficients may be manipulated in
&GAP;; though they behave, in subtle ways, quite differently than
polynomials over rings.
<P/>

The "pseudo-field" of floating-point numbers is an object in &GAP;,
called <C>FLOAT_PSEUDOFIELD</C>. (It is not really a field,
e.g. because addition of floating-point numbers in not
associative). It may be used to create indeterminates, for example as
<Example><![CDATA[
gap> x := Indeterminate(FLOAT_PSEUDOFIELD,"x");
x
gap> 2*x^2+3;
2.0*x^2+3.0
gap> Value(last,10);
203.0
]]></Example>

</Section>

<Section><Heading>Roots of polynomials</Heading>

The Jenkins-Traub algorithm has been implemented, in arbitrary
precision for MPFR and MPC.
<P/>
Furthermore, CXSC can provide complex enclosures for the roots of a
complex polynomial.

</Section>

<Section><Heading>Finding integer relations</Heading>
<#Include Label="PSLQ">
</Section>

<Section><Heading>LLL lattice reduction</Heading>

A faster implementation of the LLL lattice reduction algorithm has
also been implemented. It is accessible via the commands
<C>FPLLLReducedBasis(m)</C> and 
<C>FPLLLShortestVector(m)</C>.
<P/>

</Section>

</Chapter>

<Chapter Label="impl"><Heading>Implemented packages</Heading>

<Section><Heading>MPFR</Heading>
<#Include Label="IsMPFRFloat">
</Section>

<Section><Heading>MPFI</Heading>
<#Include Label="IsMPFIFloat">
</Section>

<Section><Heading>MPC</Heading>
<#Include Label="IsMPCFloat">
</Section>

<Section><Heading>CXSC</Heading>
<#Include Label="IsCXSCFloat">
</Section>

<Section><Heading>FPLLL</Heading>
<#Include Label="FPLLL">
</Section>

</Chapter>

</Body>

<Bibliography Databases="floatbib.xml"/>
<TheIndex/>

</Book>

=== fingolfin/gap-osx-binary/lib/gap/pkg/ExamplesForHomalg/doc/ExamplesForHomalg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
	  [
	  <!ENTITY see '<Alt Only="LaTeX">$\to$</Alt><Alt Not="LaTeX">--&gt;</Alt>'>
	  <!ENTITY GAP4 '<Package>GAP4</Package>'>
	  <!ENTITY Maple '<Package>Maple</Package>'>
	  <!ENTITY Mathematica '<Package>Mathematica</Package>'>
	  <!ENTITY Singular '<Package>Singular</Package>'>
	  <!ENTITY Plural '<Package>Plural</Package>'>
	  <!ENTITY Sage '<Package>Sage</Package>'>
	  <!ENTITY python '<Package>python</Package>'>
	  <!ENTITY cython '<Package>cython</Package>'>
	  <!ENTITY C '<Package>C</Package>'>
	  <!ENTITY MAGMA '<Package>MAGMA</Package>'>
	  <!ENTITY IO '<Package>IO</Package>'>
	  <!ENTITY homalg "<Package>homalg</Package>">
	  <!ENTITY LIRNG "<Package>LIRNG</Package>">
	  <!ENTITY LIMAT "<Package>LIMAT</Package>">
	  <!ENTITY COLEM "<Package>COLEM</Package>">
	  <!ENTITY LIMOD "<Package>LIMOD</Package>">
	  <!ENTITY LIMOR "<Package>LIMOR</Package>">
	  <!ENTITY LICPX "<Package>LICPX</Package>">
	  <!ENTITY ExamplesForHomalg "<Package>ExamplesForHomalg</Package>">
	  <!ENTITY alexander "<Package>alexander</Package>">
	  <!ENTITY Gauss "<Package>Gauss</Package>">
	  <!ENTITY GaussForHomalg "<Package>GaussForHomalg</Package>">
	  <!ENTITY IO_ForHomalg "<Package>IO_ForHomalg</Package>">
	  <!ENTITY RingsForHomalg "<Package>RingsForHomalg</Package>">
	  <!ENTITY LessGenerators "<Package>LessGenerators</Package>">
	  <!ENTITY Yoneda "<Package>Yoneda</Package>">
	  <!ENTITY Sheaves "<Package>Sheaves</Package>">
	  <!ENTITY SCO "<Package>SCO</Package>">
	  <!ENTITY GAPDoc "<Package>GAPDoc</Package>">
	  ]
	  >

<!--

  ExamplesForHomalg.xml          ExamplesForHomalg package documentation            Mohamed Barakat
                                                                                     Simon Goertzen
                                                                             Markus Lange-Hegermann

  Copyright (C) 2007-2008, Lehrstuhl B fÃ¼r Mathematik, RWTH-Aachen University

-->

<Book Name="ExamplesForHomalg">

<#Include SYSTEM "title.xml">

<!--  TableOfContents  . . . . . .  generate a table of contents   -->
<TableOfContents/>

<!--  chapters of the book  --> 
<Body>

<Index>&ExamplesForHomalg;</Index>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "install.xml">
<#Include SYSTEM "examples.xml">
</Body>

<Bibliography Databases="ExamplesForHomalgBib.xml"/>

<!--  And finally an index as well   -->
<TheIndex/>

</Book>

=== fingolfin/gap-osx-binary/lib/gap/pkg/kan-1.07/doc/manual.xml
<!-- ------------------------------------------------------------------- -->
<!--                                                                     -->
<!--  manual.xml           KAN documentation              Chris Wensley  -->
<!--                                                    & Anne Heyworth  -->
<!--  version 1.07, 09/10/2013                                           -->
<!--                                                                     -->
<!--  Copyright (C) 2005-2013, Anne Heyworth and Chris Wensley,          --> 
<!--  School of Computer Science, Bangor University, U.K.                --> 
<!--                                                                     -->
<!-- ------------------------------------------------------------------- -->

<?xml version="1.0" encoding="UTF-8"?>

<!-- Reading data chunk from the PackageInfo.g file --> 

<!DOCTYPE Book SYSTEM "gapdoc.dtd"
  [<!ENTITY kan "<Package>Kan</Package>"> 
   <#Include Label="PKGVERSIONDATA"> 
  ]> 

<Book Name="Kan"> 

<TitlePage>
  <Title>&kan;</Title>
  <Subtitle>A package for Induced Category Actions</Subtitle>
  <Version>Version &VERSION;</Version>   
  <Date>&RELEASEDATE;</Date> 
  <Author> Anne Heyworth
  </Author>    
  <Author> Chris Wensley
    <Email>c.d.wensley@bangor.ac.uk</Email>
    <Homepage>http://www.bangor.ac.uk/~mas023/</Homepage>
    <Address>
      School of Computer Science, Bangor University,<Br/>
      Dean Street, Bangor, Gwynedd, LL57 1UT, U.K.
    </Address>
  </Author>

<Abstract>
The &kan; package was originally implemented in 1997 using 
the &GAP; 3 language, to compute induced actions of categories, 
when the first author was studying for a Ph.D. in Bangor.
<P/>
This reduced version only provides functions for the computation of 
normal forms of representatives of double cosets of finitely presented groups. 
<P/>
Bug reports, suggestions and comments are, of course, welcome. 
Please contact the second author at     
<Email>c.d.wensley@bangor.ac.uk</Email>.
</Abstract>

<Copyright> 
<Index>License</Index>
&copyright; 2005-2013 Anne Heyworth and Chris Wensley <P/>

<Package>kan</Package> is free software; you can redistribute it 
and/or modify it under the terms of the 
<URL Text="GNU General Public License">http://www.fsf.org/licenses/gpl.html</URL> 
as published by the Free Software Foundation; 
either version 2 of the License, or (at your option) any later version.
</Copyright> 

<Acknowledgements>
This documentation was prepared with the <Package>GAPDoc</Package> 
package of Frank L&#xfc;beck and Max Neunh&#xf6;ffer. 
</Acknowledgements>

</TitlePage>

<TableOfContents/>

<Body>

<#Include SYSTEM "intro.xml">
<#Include SYSTEM "dcrws.xml">
<#Include SYSTEM "history.xml">

</Body>

<Bibliography Databases="manual"/>

<TheIndex/>

</Book>

=== fingolfin/gap-osx-binary/lib/gap/pkg/recogbase-1.2.2/doc/recogbase.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE Book SYSTEM "gapdoc.dtd">

<!--

  recogbase.xml          recogbase package documentation                
                                                                Max Neunhoeffer
                                                                and Ákos Seress

  Copyright (C) 2005-2008 by the authors.

-->

<Book Name="recogbase">

<TitlePage>
    <Title>GAP 4 Package <Package>recogbase</Package></Title>
    <Subtitle>A framework for group recognition</Subtitle>
    <Version>
      <#Include SYSTEM "../VERSION">
    </Version>
    <Author>Max Neunhoeffer
    <Address>School of Mathematics and Statistics, Mathematical
        Institute, North Haugh, St Andrews,
        Fife, KY16 9SS, Scotland, UK</Address>
    <Email>neunhoef@mcs.st-and.ac.uk</Email>
    <Homepage>http://www-groups.mcs.st-and.ac.uk/~neunhoef/</Homepage>
    </Author>
    <Author>Ákos Seress
<Address>
Department of Mathematics,
The Ohio State University,
231 W 18th Avenue,
Columbus, OH 43210 USA 
</Address>
    <Email>akos@math.ohio-state.edu</Email>
    <Homepage>http://www.math.ohio-state.edu/people/display/display.php?ID=302
    </Homepage>
    </Author>
    <Date>March 2014</Date>

<Copyright>
  &copyright; 2005-2011 by Max Neunhöffer and Ákos Seress<P/>

  This package may be distributed under the terms and conditions of the
  GNU Public License Version 3 or (at your option) any later version.
</Copyright>

</TitlePage>

<!--  TableOfContents  . . . . . .  generate a table of contents   -->
<TableOfContents/>

<!--  The only chapter of the book  --> 
<Body>
<#Include SYSTEM "intro.xml">
<#Include SYSTEM "install.xml">
<#Include SYSTEM "methsel.xml">
<#Include SYSTEM "recognition.xml">
<#Include SYSTEM "afterrecog.xml">
</Body>

<Bibliography Databases="recogbase"/>

<!--  And finally an index as well   -->
<TheIndex/>

</Book>
